server:
  port: 8088

---

spring:
  profiles: default
  cloud:
    gateway:
#<<< API Gateway / Routes
      routes:
        - id: community
          uri: http://localhost:8082
          predicates:
            - Path=/posts/**, /comments/**, /undefined/**, /undefined/**, 
        - id: tree
          uri: http://localhost:0
          predicates:
            - Path=/plants/**, 
        - id: user
          uri: http://localhost:0
          predicates:
            - Path=/users/**, /memberRequestLists/**, 
        - id: dashboard
          uri: http://localhost:0
          predicates:
            - Path=, /maps/**
        - id: chatbot
          uri: http://localhost:0
          predicates:
            - Path=/chatbots/**, 
        - id: ai
          uri: http://localhost:0
          predicates:
            - Path=/undefined/**, /undefined/**, 
        - id: frontend
          uri: http://localhost:8080
          predicates:
            - Path=/**
#>>> API Gateway / Routes
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true


---

spring:
  profiles: docker
  cloud:
    gateway:
      routes:
        - id: community
          uri: http://community:8080
          predicates:
            - Path=/posts/**, /comments/**, /undefined/**, /undefined/**, 
        - id: tree
          uri: http://tree:8080
          predicates:
            - Path=/plants/**, 
        - id: user
          uri: http://user:8080
          predicates:
            - Path=/users/**, /memberRequestLists/**, 
        - id: dashboard
          uri: http://dashboard:8080
          predicates:
            - Path=, 
        - id: chatbot
          uri: http://chatbot:8080
          predicates:
            - Path=/chatbots/**, 
        - id: ai
          uri: http://ai:8080
          predicates:
            - Path=/undefined/**, /undefined/**, 
        - id: frontend
          uri: http://frontend:8080
          predicates:
            - Path=/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true

server:
  port: 8080
